### ISSUE TITLE
Failed to add client

### ISSUE THREAD

**Issue by gchers** [peperunas/wireguard-configure#4]
Heyia, getting an error with `add-client`.

Steps to reproduce.

```
cd /etc/wireguard
wireguard-configure generate-example > test.toml
wireguard-configure add-client test.toml testclient  -a 10.0.1.0/24 -i 10.0.1.3
```

On the other hand, operations like the following one do work properly:
```
wireguard-configure router-config test.toml
```

(Example) config file generated as above:

```
---
router:
  name: vpn-router
  internal_address: 10.0.1.1/24
  external_address:
    address: vpn.com
    port: 31337
  private_key: eB5/JINEkG7IxSEf/Urtd90QpQuTPbp/nkzR+/etgUM=
  public_key: dqpeuORznwsrNxoX7Qh53Ix+rZU8kwEbgJXTief7dB4=
clients:
  - name: client-a
    internal_address: 10.0.1.2
    allowed_ips:
      - 0.0.0.0/0
    dns: 10.0.1.1
    persistent_keepalive: 25
    private_key: AASEMZ5TyfnCL4PnN7zIMB5Djc+wjZVo1jVFcJkzKVM=
    public_key: zrKXYLHQdVZlqE34+donzCBdkurj59xR73AoUL5yZGs=
  - name: client-b
    internal_address: 10.0.1.3
    allowed_ips:
      - 10.0.1.0/24
    dns: ~
    persistent_keepalive: 25
    private_key: 8PTFsN+/o3xHV872E0n5qAEkh/KktzidkUnebafwyEA=
    public_key: NF22ZCqqMyfZyfzQpCCINmhy76n3jlGSadnAcej4YGk=
```
